// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Note struct {
	ID        int64
	NoteID    string
	Title     string
	Tags      string
	Content   string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
	DeletedAt sql.NullString
}

type User struct {
	ID          int64
	UserID      string
	Username    string
	Displayname string
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
	DeletedAt   sql.NullString
}

type UserNote struct {
	UserID string
	NoteID string
}
