// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Note struct {
	NoteID    string     `json:"noteId"`
	Title     string     `json:"title"`
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	Tags      []*PostTag `json:"tags"`
}

type NoteByAuthor struct {
	Note   *Note `json:"note"`
	Author *User `json:"author"`
}

type Notes struct {
	Count  int     `json:"count"`
	Notes  []*Note `json:"notes"`
	Author *User   `json:"author"`
}

type PostTag struct {
	Name string `json:"name"`
}

type Query struct {
}

type User struct {
	UserID      string `json:"userId"`
	Username    string `json:"username"`
	Displayname string `json:"displayname"`
}
